# config about the data

"batch_size": 64,
"shuffle": True,
"num_workers": 4,
"data_dir": "/data/scratch/public/mlrsnet/data/Images",
"csv_file": "/data/scratch/public/mlrsnet/data/mlrsnet_train.csv"

# config about the model
"learning_rate": 0.0001,
"pretrained": true,
"threshold": 0.5,
"metrics": ["accuracy", "precision", "recall", "f1_score"]
